void printMenu(void);
int obtem_rand(int min, int max);
int verifyUserName(clients *users, int *nUsers, char *username);
clients *addUser(clients *users, int *nUsers, char *username, int pid, char *fifostr);
char *getUsernameFromfifo(clients *users, char *fifo);
void listusers(clients *users);
void closeapp(int sig);
void desligarClientes(clients *users);
clients *removeUser(clients *users, char *cp, int *nUsers);
void verificador(char *verify);